### ISSUE TITLE
iso: /etc/os-release causes failures in Advantage APT and MOTD

### ISSUE THREAD

**Issue by vossenjp** [linuxmint/-mint20.2-beta#29]
Several weeks ago I started getting these failures in my logs:
```
Jun 18 03:16:22 hostname python3[3568780]: Traceback (most recent call last):
Jun 18 03:16:22 hostname python3[3568780]:   File "/usr/lib/ubuntu-advantage/ua_update_messaging.py", line 302, in <module>
Jun 18 03:16:22 hostname python3[3568780]:     update_apt_and_motd_messages(cfg=cfg)
Jun 18 03:16:22 hostname python3[3568780]:   File "/usr/lib/ubuntu-advantage/ua_update_messaging.py", line 283, in update_apt_and_motd_messages
Jun 18 03:16:22 hostname python3[3568780]:     series = util.get_platform_info()["series"]
Jun 18 03:16:22 hostname python3[3568780]:   File "/usr/lib/python3/dist-packages/uaclient/util.py", line 331, in get_platform_info
Jun 18 03:16:22 hostname python3[3568780]:     raise RuntimeError(
Jun 18 03:16:22 hostname python3[3568780]: RuntimeError: Could not parse /etc/os-release VERSION: 20 (Ulyana) (modified to 20 (Ulyana))
Jun 18 03:16:22 hostname systemd[1]: ua-messaging.service: Main process exited, code=exited, status=1/FAILURE
Jun 18 03:16:22 hostname systemd[1]: ua-messaging.service: Failed with result 'exit-code'.
Jun 18 03:16:22 hostname systemd[1]: Failed to start Ubuntu Advantage APT and MOTD Messages.
```

This is caused by:
```
$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="20 (Ulyana)"                  # <<<<<<< THIS LINE should be 20.0
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20"
VERSION_ID="20"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyana
UBUNTU_CODENAME=focal
```

Because `/usr/lib/python3/dist-packages/uaclient/util.py` (from "ubuntu-advantage-tools") has:
```
...
     44 REGEX_OS_RELEASE_VERSION = r"(?P<release>\d+\.\d+) (LTS )?\((?P<series>\w+).*"
...
    329     match = re.match(REGEX_OS_RELEASE_VERSION, version)
    330     if not match:
    331         raise RuntimeError(
    332             "Could not parse /etc/os-release VERSION: {} (modified to"
    333             " {})".format(os_release["VERSION"], version)
    334         )
...
```
And clearly `VERSION="20 (Ulyana)"` does not contain `\.\d` so it will never match `(?P<release>\d+\.\d+)`.

Personally, I've never liked the inconsistency of Mint "20" vs. "21.1", etc.  I've always thought it should start "20.0".

I've filed this here because:
```
$ apt policy base-files
base-files:
  Installed: 20.0.1
  Candidate: 20.0.1
  Version table:
 *** 20.0.1 700
        700 http://mirror.cs.jmu.edu/pub/linuxmint/packages ulyana/upstream amd64 Packages
        100 /var/lib/dpkg/status
     11ubuntu5.3 500
        500 http://mirror.math.princeton.edu/pub/ubuntu focal-updates/main amd64 Packages
     11ubuntu5 500
        500 http://mirror.math.princeton.edu/pub/ubuntu focal/main amd64 Packages
```

And I think the bug is in Mint's `os-release::VERSION` and not the regexp in "ubuntu-advantage-tools," though that could be hacked to something like `(?P<release>\d+(\.\d+)?)` also.

Needless to say, when I get around to upgrading to 20.x the problem will go away.  Until "21"...

I've just tried a short-term fix of manually editing `/etc/os-release` and changing to "20.0", but I don't know if that will break anything else yet.

**Comment by clefebvre** [comment]
ubuntu-advantage-tools will be removed from future ISOs.
